package view;


import controller.CKehadiran;
import controller.CKoneksiDB;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.Locale;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import model.MHadir;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gilsur
 */
public class Absensi extends javax.swing.JFrame {

    /**
     * Creates new form Absensi
     */
    private int waktumulai =0;
    private int detik;
    private int kesempatan;
    List<MHadir> ambil   = new ArrayList<MHadir>();    
    Date jam = new Date();
    MHadir pegawai = new MHadir(); 
    private boolean status1 = false;
    private boolean status2 = false;
    private boolean status3 = false;
    private boolean status_masuk = false;
    private boolean status_hadir = false;
    
    CKehadiran kehadiran = new CKehadiran();
    
    public Absensi() {
        initComponents();  
        this.setLocationRelativeTo(this);
        popUp.setVisible(false);
        
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("dd MMMMM yyyy");
        jTanggal.setText(sdf.format(cal.getTime()));
        
        new Thread(){
            @Override
            public void run(){
                while(waktumulai == 0){
                    String time;
                    Calendar kalender = new GregorianCalendar();
                    int jam = kalender.get(Calendar.HOUR);
                    int menit = kalender.get(Calendar.MINUTE);
                    int detik = kalender.get(Calendar.SECOND);
                    int am = kalender.get(Calendar.AM_PM);
                    if(am == 0){
                        time = jam + ":" + menit + ":" + detik;
                    }else{
                        time = (jam+12) + ":" + menit + ":" + detik;
                    }
                    
                    tampil_jam.setText(time);               
                }  
            }
        }.start();
    }
    
    public void show_tanggal(){
        Calendar kalender = new GregorianCalendar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jTanggal = new javax.swing.JLabel();
        label_error_message = new javax.swing.JLabel();
        tampil_jam = new javax.swing.JLabel();
        txtNip = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        popUp = new javax.swing.JPanel();
        foto_pegawai = new javax.swing.JLabel();
        label_jamkerja = new javax.swing.JLabel();
        label_NamaPegawai = new javax.swing.JLabel();
        label_JabatanPegawai = new javax.swing.JLabel();
        jPINField = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jKeterangan = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Absensi Pegawai");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(250, 80, 0, 0));
        setIconImages(null);
        setMaximumSize(new java.awt.Dimension(512, 370));
        setMinimumSize(new java.awt.Dimension(512, 370));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setToolTipText("");
        mainPanel.setAutoscrolls(true);
        mainPanel.setMinimumSize(new java.awt.Dimension(512, 370));
        mainPanel.setPreferredSize(new java.awt.Dimension(512, 370));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTanggal.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jTanggal.setText(" ");
        jTanggal.setToolTipText(null);
        mainPanel.add(jTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 137, 220, 20));

        label_error_message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_error_message.setToolTipText(null);
        mainPanel.add(label_error_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 490, 40));

        tampil_jam.setFont(new java.awt.Font("DS-Digital", 0, 36)); // NOI18N
        tampil_jam.setText("03:00:00");
        tampil_jam.setToolTipText(null);
        mainPanel.add(tampil_jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 127, 160, -1));

        txtNip.setBackground(new java.awt.Color(249, 249, 249));
        txtNip.setFont(new java.awt.Font("Lucida Gr", 0, 24)); // NOI18N
        txtNip.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNip.setToolTipText("Masukan NIP anda");
        txtNip.setInheritsPopupMenu(true);
        txtNip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNipActionPerformed(evt);
            }
        });
        txtNip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNipKeyReleased(evt);
            }
        });
        mainPanel.add(txtNip, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 290, 50));

        jLabel1.setFont(new java.awt.Font("Lucida G", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setToolTipText(null);
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Masukan NIP"));
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 310, 80));

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setForeground(new java.awt.Color(0, 153, 204));
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        mainPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/layout_absen_abc.jpg"))); // NOI18N
        jLabel2.setToolTipText(null);
        mainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        popUp.setMinimumSize(new java.awt.Dimension(512, 370));
        popUp.setPreferredSize(new java.awt.Dimension(512, 370));
        popUp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foto_pegawai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foto_pegawai.setText("foto");
        foto_pegawai.setToolTipText(null);
        popUp.add(foto_pegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 180, 230));

        label_jamkerja.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        label_jamkerja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_jamkerja.setText("ba");
        label_jamkerja.setToolTipText(null);
        popUp.add(label_jamkerja, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 220, -1));

        label_NamaPegawai.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        label_NamaPegawai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_NamaPegawai.setText("sa");
        label_NamaPegawai.setToolTipText(null);
        popUp.add(label_NamaPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 220, 20));

        label_JabatanPegawai.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        label_JabatanPegawai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_JabatanPegawai.setText("a");
        label_JabatanPegawai.setToolTipText(null);
        popUp.add(label_JabatanPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 220, -1));

        jPINField.setToolTipText("Masukan PIN 4-Digit");
        jPINField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPINFieldActionPerformed(evt);
            }
        });
        jPINField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPINFieldKeyReleased(evt);
            }
        });
        popUp.add(jPINField, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 263, 190, 40));

        jLabel7.setFont(new java.awt.Font("Lucida G", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setToolTipText(null);
        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Masukan PIN"));
        popUp.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 205, 60));

        jKeterangan.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jKeterangan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jKeterangan.setText("Masukan PIN");
        jKeterangan.setToolTipText(null);
        popUp.add(jKeterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 210, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/layout_popUp.jpg"))); // NOI18N
        jLabel4.setToolTipText(null);
        popUp.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 512, 370));

        getContentPane().add(popUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 512, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
                
    private void txtNipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNipActionPerformed

    private void txtNipKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNipKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String nip;
            jPINField.setText(null);
            jKeterangan.setText("Masukan PIN");
            kesempatan = 4;
            status1 = false;
            status2 = false;
            status3 = false;
            boolean status_pegawai, blokir;
            nip = txtNip.getText();    
            pegawai.setNIP(nip);
            if(!"".equals(nip)){        
            try{
                //cek apakah pegawai ada di tabel pegawai
                status_pegawai = kehadiran.cek_pegawai(pegawai);
                blokir = kehadiran.cek_statusBlock(pegawai);
                if(status_pegawai == true && blokir == true){
                        //cek dia harusnya masuk jam berapa
                        SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");
                        String jam_sekarang = format.format(jam.getTime());

                        ambil = kehadiran.ambil(pegawai);

                        String data[] = new String[5];
                        for(MHadir h : ambil){
                            data[0] = h.getNama();
                            data[1] = h.getJabatan();
                            data[2] = h.getId_Jam();
                            data[3] = h.getFoto();  
                        }

                        Time waktu[] = new Time[4];
                        for(MHadir h : ambil){
                            waktu[0] = h.getMasukStart();
                            waktu[1] = h.getKerjaStart();
                            waktu[2] = h.getKerjaEnd();
                            waktu[3] = h.getKeluarEnd();
                        }        

                        Time longjam = Time.valueOf(jam_sekarang);

                        long lj = longjam.getTime();
                        long mm = waktu[0].getTime();
                        long tg = waktu[1].getTime();
                        long mk = waktu[2].getTime();
                        long ks = waktu[3].getTime();
                        

                        label_NamaPegawai.setText(data[0]);
                        label_JabatanPegawai.setText(data[1]);
                        foto_pegawai.setIcon(new javax.swing.ImageIcon("../foto/"+data[3]));
                        foto_pegawai.setText("");
                        label_jamkerja.setText(waktu[1].toString()+" - "+waktu[2].toString());
                        jPINField.requestFocus();

                        //cek apakah pegawai tsb sudah absen masuk atau belum
                        status_hadir = kehadiran.cek_kehadiran(pegawai);
                        
                        //cek masuk tepat waktu atau telat true=tepat waktu
                        status_masuk = kehadiran.cek_statusMasuk(pegawai);
                        
                        // belum absen
                        if(status_hadir == true){
                            
                            //masuk kerja
                            if(mm < lj && lj < tg ){
                                status1 = true;
                                popUp.setVisible(true);
                                mainPanel.setVisible(false);
                            }
                            //saat kerja
                            else if(tg < lj && lj < mk){
                                status2 = true;
                                popUp.setVisible(true);
                                mainPanel.setVisible(false);
                            }
                            //selesai bekerja
                            else if(mk < lj && lj < ks){
                                javax.swing.JOptionPane.showMessageDialog(this, "Maaf anda tidak diperkenakan masuk, Lakukan absen saat jam masuk pada pukul "+waktu[1], "Maaf", JOptionPane.ERROR_MESSAGE);
                            }
                        }
                        // sudah absen
                        else if(status_hadir == false) {
                            //masuk kerja
                            if(mm < lj && lj < tg ){
                                javax.swing.JOptionPane.showMessageDialog(this, "Maaf anda telah melakukan Absen", "Maaf", JOptionPane.WARNING_MESSAGE);
                            }
                            //saat kerja
                            else if(tg < lj && lj < mk){
                                javax.swing.JOptionPane.showMessageDialog(this, "Maaf anda telah melakukan Absen, Lakukan absen saat jam pulang pada pukul "+waktu[2], "Maaf", JOptionPane.ERROR_MESSAGE);
                            }
                            //selesai bekerja
                            else if(mk < lj && lj < ks){
                                status3=true;
                                popUp.setVisible(true);
                                mainPanel.setVisible(false);
                            }
                        }
                        txtNip.setText("");
                        txtNip.requestFocus();
                   
                } else if(status_pegawai == true && blokir == false){
                    javax.swing.JOptionPane.showMessageDialog(this, "MAAF UNTUK HARI INI NIP ANDA DI BLOKIR!\nSILAHKAN HUBUNGI ADMIN", "BLOKIR", JOptionPane.ERROR_MESSAGE);
                } else if(status_pegawai == false && blokir == true) {
                   label_error_message.setText("Pastikan NIP yang anda masukan benar");
                }

            }catch(SQLException ex){
                javax.swing.JOptionPane.showMessageDialog(this, ex, "ERROR", JOptionPane.ERROR_MESSAGE);
                label_error_message.setText("Kesalahan Database "+ ex); 
            }
        }else{
            label_error_message.setText("Masukan NIP");  
        }
        txtNip.setText("");
    }
    
    }//GEN-LAST:event_txtNipKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPINFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPINFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPINFieldActionPerformed

    private void jPINFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPINFieldKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try {
                status_masuk = kehadiran.cek_statusMasuk(pegawai);
                String PINS = new String(jPINField.getPassword());
                String PPns = kehadiran.cek_PIN(pegawai);
                if(PPns.equals(PINS)){
                    mainPanel.setVisible(true);
                    popUp.setVisible(false);
                    if(status1==true){
                        kehadiran.masuk(pegawai.getNIP(), "Hadir (Sedang Bekerja)");
                        javax.swing.JOptionPane.showMessageDialog(this, "Anda Berhasil melakuan Absensi, Selamat Bekerja ", "Selamat Datang", JOptionPane.INFORMATION_MESSAGE);
                        status1 = false;
                    }else  if(status2==true){
                        kehadiran.masuk(pegawai.getNIP(), "Telat (Sedang Bekerja)");
                        javax.swing.JOptionPane.showMessageDialog(this, "Anda telah melakukan absen dengan telat, Selamat Bekerja" , "Telat", JOptionPane.WARNING_MESSAGE);
                        status2 = false;
                    }else if(status3==true && status_masuk==true){
                        kehadiran.keluar(pegawai.getNIP(), "Hadir");
                        javax.swing.JOptionPane.showMessageDialog(this, "Anda berhasil melakuan Absen dengan Tepat Waktu, Terimakasih" , "Terimakasih", JOptionPane.INFORMATION_MESSAGE);
                        status2 = false;
                    }else if(status3==true && status_masuk==false){
                        kehadiran.keluar(pegawai.getNIP(), "Telat Masuk");
                        javax.swing.JOptionPane.showMessageDialog(this, "Anda berhasil melakuan Absen dengan terlambat datang, Terimakasih" , "Terimakasih", JOptionPane.INFORMATION_MESSAGE);
                        status2 = false;
                    } 
                }else{
                    jKeterangan.setText("<html>Maaf PIN yang anda Masukan salah <br/> Kesemempatan anda tinggal "+ (kesempatan-1) + "x lagi");
                    jPINField.setText(null);
                    jPINField.requestFocus();
                    kesempatan = kesempatan - 1;
                    if(kesempatan == 0){
                        javax.swing.JOptionPane.showMessageDialog(this, "MAAF UNTUK HARI INI NIP ANDA DI BLOKIR!\nSILAHKAN HUBUNGI ADMIN", "BLOKIR", JOptionPane.ERROR_MESSAGE);
                            if(status_hadir==false){
                               if(status_masuk==true){
                                   kehadiran.keluar(pegawai.getNIP(), "BLOCK (ABSEN PULANG)");
                               }else{
                                   kehadiran.keluar(pegawai.getNIP(), "BLOCK + TELAT (ABSEN PULANG)");
                               }
                                
                            }else{
                                if(status_masuk==true){
                                    kehadiran.masuk(pegawai.getNIP(), "BLOCK (ABSEN DATANG)"); //FIX
                                }else{
                                    kehadiran.masuk(pegawai.getNIP(), "BLOCK + TELAT (ABSEN DATANG)");
                                }
                            }
                        mainPanel.setVisible(true);
                        popUp.setVisible(false);
                    }
                }
            } catch (SQLException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, ex , "ERROR", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(Absensi.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
    }//GEN-LAST:event_jPINFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Absensi().setVisible(true);
            }
            
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel foto_pegawai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jKeterangan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPINField;
    private javax.swing.JLabel jTanggal;
    private javax.swing.JLabel label_JabatanPegawai;
    private javax.swing.JLabel label_NamaPegawai;
    private javax.swing.JLabel label_error_message;
    private javax.swing.JLabel label_jamkerja;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel popUp;
    private javax.swing.JLabel tampil_jam;
    private javax.swing.JTextField txtNip;
    // End of variables declaration//GEN-END:variables
}